---
name: Module-Metadata-Changes
version: 1.01
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Manage a module's CHANGES file
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  Config::IniFiles: 0
  DateTime::Format::HTTP: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::W3CDTF: 0
  HTML::Entities::Interpolate: 0
  HTML::Template: 0
  Test::More: 0
  Test::Pod: 0
  version: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  Module::Metadata::Changes:
    file: lib/Module/Metadata/Changes.pm
    version: 1.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
